import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/modules/footer";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/modules/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar></Navbar>


<div className="min-h-screen w-full relative">
  {/* Azure Depths Background */}
  <div
    className="
      absolute inset-0 z-0
      bg-[radial-gradient(125%_125%_at_50%_10%,#ffffff_40%,#e0e0ff_100%)]
      dark:bg-[radial-gradient(125%_125%_at_50%_10%,#000000_40%,#010133_100%)]
    "
  />

  {/* Foreground content */}
  <div className="relative z-10">
    <div className="min-h-[calc(100vh-150px)] relative">
      {children}
    </div>
  </div>
</div>

      

          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}

